export {default as Home} from './Home'
export {default as Blog} from './Blog'
export {default as AppliedJob} from './AppliedJob'
export {default as Statics} from './Statics'
export {default as JobCategoryList} from './JobCategoryList'